name: flutter_portugal_home
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.4.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.0.4
  google_fonts: ^1.0.0  
  cloud_firestore: ^0.13.5
  cloud_firestore_web: ^0.1.1+2
  provider: ^4.0.5
  url_launcher: ^5.4.5
  flutter_html: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true
